# Generated by Django 4.2.6 on 2023-11-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intérprete",
            fields=[
                ("idInterprete", models.AutoField(primary_key=True, serialize=False)),
                ("nameInterprete", models.TextField()),
                ("infoIntérprete", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Promotor",
            fields=[
                ("idPromotor", models.AutoField(primary_key=True, serialize=False)),
                ("namePromotor", models.TextField()),
                ("infoPromotor", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Festival",
            fields=[
                ("idFestival", models.AutoField(primary_key=True, serialize=False)),
                ("nombreFestival", models.TextField()),
                ("infoFestival", models.TextField()),
                ("fecha", models.TextField()),
                (
                    "idPromotor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appPromoConcert.promotor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Actuación",
            fields=[
                ("idActuacion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "idFestival",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appPromoConcert.festival",
                    ),
                ),
                (
                    "idInterprete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appPromoConcert.intérprete",
                    ),
                ),
            ],
        ),
    ]
