# Generated by Django 4.2.6 on 2023-11-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appPromoConcert", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Actuación",
            new_name="Actuacion",
        ),
        migrations.RenameModel(
            old_name="Intérprete",
            new_name="Interprete",
        ),
    ]
