# Generated by Django 4.2.7 on 2023-11-08 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPromoConcert', '0002_rename_actuación_actuacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='idPromotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festivales', to='appPromoConcert.promotor'),
        ),
    ]
