# Generated by Django 4.2.7 on 2023-11-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPromoConcert', '0003_alter_festival_idpromotor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuacion',
            name='idFestival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='appPromoConcert.festival'),
        ),
        migrations.AlterField(
            model_name='actuacion',
            name='idInterprete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='appPromoConcert.interprete'),
        ),
    ]
