# Generated by Django 4.2.7 on 2023-11-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPromoConcert', '0004_interprete_festivales_delete_actuacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interprete',
            old_name='infoIntérprete',
            new_name='infoInterprete',
        ),
    ]
