# Generated by Django 4.2.7 on 2023-11-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPromoConcert', '0005_rename_infointérprete_interprete_infointerprete'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
    ]
