# Generated by Django 4.2.7 on 2023-11-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPromoConcert', '0006_promotor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Image'),
        ),
    ]
