# Generated by Django 4.2.7 on 2023-11-21 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interprete',
            fields=[
                ('idInterprete', models.AutoField(primary_key=True, serialize=False)),
                ('nameInterprete', models.TextField()),
                ('infoInterprete', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('idPromotor', models.AutoField(primary_key=True, serialize=False)),
                ('namePromotor', models.TextField()),
                ('infoPromotor', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('idFestival', models.AutoField(primary_key=True, serialize=False)),
                ('nombreFestival', models.TextField()),
                ('infoFestival', models.TextField()),
                ('fecha', models.TextField()),
                ('interpretes', models.ManyToManyField(to='appPromoConcert.interprete')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festivales', to='appPromoConcert.promotor')),
            ],
        ),
    ]
